packages:
  - apps/*
  - packages/*

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  protobufjs: true
  unrs-resolver: true

catalog:
  react: ^19.2.8
  react-dom: ^19.2.8
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  firebase: ^12.17.1
  '@material-symbols-svg/react': ^0.13.0
  wouter: ^3.10.0
  zustand: ^5.0.14
  typescript: ^7.0.2
  vite: ^8.2.1
  sass-embedded: ^1.100.0
  '@types/node': ^26.1.2
  '@vitejs/plugin-react': ^6.0.5
  babel-plugin-react-compiler: ^1.0.0
  globals: ^17.9.0
  '@rolldown/plugin-babel': ^0.2.3

minimumReleaseAgeExclude:
  - vite@8.2.1
