import {
  ArrowCounterClockwiseIcon,
  BeerBottleIcon,
  BeerSteinIcon,
  ChampagneIcon,
  ChartBarIcon,
  FloppyDiskIcon,
  GearSixIcon,
  GenderFemaleIcon,
  GenderMaleIcon,
  GithubLogoIcon,
  PencilIcon,
  PlusIcon,
  SignOutIcon,
  UserCircleIcon,
  WineIcon,
  XIcon,
} from '@phosphor-icons/react';

export const icons = {
  SignOutIcon,
  BeerBottleIcon,
  BeerSteinIcon,
  WineIcon,
  ChampagneIcon,
  GearSixIcon,
  GenderMaleIcon,
  GenderFemaleIcon,
  XIcon,
  PlusIcon,
  PencilIcon,
  ChartBarIcon,
  ArrowCounterClockwiseIcon,
  FloppyDiskIcon,
  UserCircleIcon,
  GithubLogoIcon,
};
